{% set name = "sasmodels" %}
{% set version = "1.0.10" %}
{% set python_max = "3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54d979d9a6146be983aba5fd695f1b3454620708332cabb1625c7436866098d1

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - {{ compiler('c') }}
    - python >={{ python_min }},<{{ python_max }}
    - hatchling
    - hatch-requirements-txt
    - hatch-sphinx
    - hatch-vcs
    - bumps
    - docutils
    - matplotlib-base
    - numpy
    - scipy
    - siphash24
    - sphinx
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - bumps
    - matplotlib-base
    - numpy
    - pyopencl
    - scipy
    - siphash24

test:
  requires:
    - python {{ python_min }}
  imports:
    - sasmodels
    - sasmodels.custom
    - sasmodels.models

about:
  home: http://www.sasview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package for calculation of small angle scattering models using OpenCL
  dev_url: https://github.com/SasView/sasmodels

extra:
  recipe-maintainers:
    - tschoonj
    - mrakitin
