travis:
  secure:
    BINSTAR_TOKEN: OJUts9EM+U7g12byGB8aIt79tykO21zVBTJuGxgDYfod5riap/nocBBg79t9o5/LC0Q20cJ+ZW5a/Q3ZGyT9klvrmpYlh3ROdw8O2d9qaSxxYkV1E8kcV0GMZnh8Z+fqAodRQXF8YarP9jGf0k8aAIsbc7xkn088Chqr1ASHTuMeACLhBgsjq9ATnfCapC5Nhtn7lBwfbgpYswNyZxpGWiYDRZje4MCWDEddQjr5Ncu5yg58X5t5eJvQe5Rm5E5fYePtI5uSx2QymvCLgBjof8RHBiFMi5wQEhYIImmZv3psRe20+rTK79q7tC8q6G0aDEhzQjtZWE1te2q2XTYJNZHjuB55fs+r8FObICQfsfpEHGeAapSxwFRQ4sfVNPHAE8Eoui7aYsEnip+WhO+jR29C2qsd8dIZuyisHJ+HthttbtsI8itu8dgsmR4kElpQQ5L5plQD0rDdhpilTKInshdYBaMRHfHcgfOamdYkxNKfcJAQxmPZgyXiWATPhGnK2RtiqT3QF/KDCXstUnX4ygWiZcZtdsBy2czRExWjzD0MaQFaUXsrqHfCYDbSqxx5T7bmMHpUPFP5vzzDbB+NHNWkZtWvrgkk3oeQomvxPjjDW0fHtuBeci7WkqHODRPDbDPL2iR9HE3CpEqo1yn1z1Lw8n45lvimU+dImrboXtM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
